using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Helpers
{
    public class ColorsList
    {
        public List<string> Colors { get; set; } = new List<string>();

        public ColorsList()
        {
            Colors.Add("Almond");
            Colors.Add("Antique Brass");
            Colors.Add("Apricot");
            Colors.Add("Aquamarine");
            Colors.Add("Asparagus");
            Colors.Add("Atomic Tangerine");
            Colors.Add("Banana Mania");
            Colors.Add("Beaver");
            Colors.Add("Bittersweet");
            Colors.Add("Black");
            Colors.Add("Blizzard Blue");
            Colors.Add("Blue");
            Colors.Add("Blue Bell");
            Colors.Add("Blue Gray");
            Colors.Add("Blue Green");
            Colors.Add("Blue Violet");
            Colors.Add("Blush");
            Colors.Add("Brick Red");
            Colors.Add("Brown");
            Colors.Add("Burnt Orange");
            Colors.Add("Burnt Sienna");
            Colors.Add("Cadet Blue");
            Colors.Add("Canary");
            Colors.Add("Caribbean Green");
            Colors.Add("Carnation Pink");
            Colors.Add("Cerise");
            Colors.Add("Cerulean");
            Colors.Add("Chestnut");
            Colors.Add("Copper");
            Colors.Add("Cornflower");
            Colors.Add("Cotton Candy");
            Colors.Add("Dandelion");
            Colors.Add("Denim");
            Colors.Add("Desert Sand");
            Colors.Add("Eggplant");
            Colors.Add("Electric Lime");
            Colors.Add("Fern");
            Colors.Add("Forest Green");
            Colors.Add("Fuchsia");
            Colors.Add("Fuzzy Wuzzy");
            Colors.Add("Gold");
            Colors.Add("Goldenrod");
            Colors.Add("Granny Smith Apple");
            Colors.Add("Gray");
            Colors.Add("Green");
            Colors.Add("Green Blue");
            Colors.Add("Green Yellow");
            Colors.Add("Hot Magenta");
            Colors.Add("Inchworm");
            Colors.Add("Indigo");
            Colors.Add("Jazzberry Jam");
            Colors.Add("Jungle Green");
            Colors.Add("Laser Lemon");
            Colors.Add("Lavender");
            Colors.Add("Lemon Yellow");
            Colors.Add("Macaroni and Cheese");
            Colors.Add("Magenta");
            Colors.Add("Magic Mint");
            Colors.Add("Mahogany");
            Colors.Add("Maize");
            Colors.Add("Manatee");
            Colors.Add("Mango Tango");
            Colors.Add("Maroon");
            Colors.Add("Mauvelous");
            Colors.Add("Melon");
            Colors.Add("Midnight Blue");
            Colors.Add("Mountain Meadow");
            Colors.Add("Mulberry");
            Colors.Add("Navy Blue");
            Colors.Add("Neon Carrot");
            Colors.Add("Olive Green");
            Colors.Add("Orange");
            Colors.Add("Orange Red");
            Colors.Add("Orange Yellow");
            Colors.Add("Orchid");
            Colors.Add("Outer Space");
            Colors.Add("Outrageous Orange");
            Colors.Add("Pacific Blue");
            Colors.Add("Peach");
            Colors.Add("Periwinkle");
            Colors.Add("Piggy Pink");
            Colors.Add("Pine Green");
            Colors.Add("Pink Flamingo");
            Colors.Add("Pink Sherbet");
            Colors.Add("Plum");
            Colors.Add("Purple Heart");
            Colors.Add("Purple Mountain's Majesty"); 
            Colors.Add("Purple Pizzazz");
            Colors.Add("Radical Red");
            Colors.Add("Raw Sienna");
            Colors.Add("Raw Umber");
            Colors.Add("Razzle Dazzle Rose");
            Colors.Add("Razzmatazz");
            Colors.Add("Red");
            Colors.Add("Red Orange");
            Colors.Add("Red Violet");
            Colors.Add("Robin's Egg Blue"); 
            Colors.Add("Royal Purple");
            Colors.Add("Salmon");
            Colors.Add("Scarlet");
            Colors.Add("Screamin' Green"); 
            Colors.Add("Sea Green");
            Colors.Add("Sepia");
            Colors.Add("Shadow");
            Colors.Add("Shamrock");
            Colors.Add("Shocking Pink");
            Colors.Add("Silver");
            Colors.Add("Sky Blue");
            Colors.Add("Spring Green");
            Colors.Add("Sunglow");
            Colors.Add("Sunset Orange");
            Colors.Add("Tan");
            Colors.Add("Teal Blue");
            Colors.Add("Thistle");
            Colors.Add("Tickle Me Pink");
            Colors.Add("Timberwolf");
            Colors.Add("Tropical Rain Forest");
            Colors.Add("Tumbleweed");
            Colors.Add("Turquoise Blue");
            Colors.Add("Unmellow Yellow");
            Colors.Add("VioletPurple");
            Colors.Add("Violet Blue");
            Colors.Add("Violet Red");
            Colors.Add("Vivid Tangerine");
            Colors.Add("Vivid Violet");
            Colors.Add("White");
            Colors.Add("Wild Blue Yonder");
            Colors.Add("Wild Strawberry");
            Colors.Add("Wild Watermelon");
            Colors.Add("Wisteria");
            Colors.Add("Yellow");
            Colors.Add("Yellow Green");
        }
    }
}
